# Generated by Django 3.0.1 on 2019-12-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('file_desc', models.CharField(default='', max_length=200)),
                ('file_uploader', models.CharField(default='', max_length=50)),
                ('pub_date', models.DateField()),
                ('file', models.ImageField(default='', upload_to='shop/file')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
