# Generated by Django 3.0.1 on 2019-12-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unote',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
