# Generated by Django 3.0.1 on 2019-12-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unotes', '0002_auto_20191231_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unote',
            name='file',
            field=models.FileField(upload_to='file'),
        ),
    ]
