# Generated by Django 3.0.1 on 2019-12-31 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unotes', '0003_auto_20191231_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unote',
            name='file_uploader',
        ),
        migrations.RemoveField(
            model_name='unote',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='unote',
            name='status',
        ),
    ]
